name: Task 4 CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: |
        cd Task4
        npm install

    - name: Run Automated Unit Tests
      run: |
        cd Task4
        npm test

    - name: Build Docker Image
      run: |
        cd Task4
        docker build -t task4-cicd-app .